accent = "#0a0a0a"
cursor = "#0a0a0a"
foreground = "#0a0a0a"
background = "#ffffff"
selection_foreground = "#ffffff"
selection_background = "#0a0a0a"

color0 = "#c0c0c0"
color1 = "#0a0a0a"
color2 = "#0a0a0a"
color3 = "#0a0a0a"
color4 = "#0a0a0a"
color5 = "#0a0a0a"
color6 = "#0a0a0a"
color7 = "#0a0a0a"
color8 = "#d0d0d0"
color9 = "#0a0a0a"
color10 = "#0a0a0a"
color11 = "#0a0a0a"
color12 = "#0a0a0a"
color13 = "#0a0a0a"
color14 = "#0a0a0a"
color15 = "#0a0a0a"
